Fix rendering of not symbol in math block
This was being being silently dropped in my local environment and I suspect is the
cause of the failure on GitHub:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xac in position 1542: ordinal
not in range(128)